@MicroStore.OrderService_HostAddress = http://localhost:5001

POST {{MicroStore.OrderService_HostAddress}}/PlaceOrder/PlaceOrder
Content-Type: application/json

{
  "ProductId": 1,
  "Quantity": 1
}

POST {{MicroStore.OrderService_HostAddress}}/PlaceOrder/PlaceOrderWithHeartBeatController
Content-Type: application/json

{
  "ProductId": 1,
  "Quantity": 1
}